[phases.setup]
commands = ["composer install --optimize-autoloader --no-dev"]

[phases.build]
commands = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
commands = ["php artisan serve --host 0.0.0.0 --port 10000"]

[options]
runtime = "php"
