services:
  - type: web
    name: movietrack-api
    env: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://movietrack.onrender.com

      # Sin valores sensibles aquí — se añadirán desde el dashboard
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
      - key: DB_PORT
      - key: DB_DATABASE
      - key: DB_USERNAME
      - key: DB_PASSWORD
      - key: MAIL_MAILER
      - key: MAIL_HOST
      - key: MAIL_PORT
      - key: MAIL_USERNAME
      - key: MAIL_PASSWORD
      - key: MAIL_ENCRYPTION
      - key: MAIL_FROM_ADDRESS
      - key: MAIL_FROM_NAME
      - key: CLOUDINARY_URL
